version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install ".[dev]"
      - run:
          name: Run tests
          command: make test

workflows:
  test:
    jobs:
      - test
